//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUploadDownload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFileDownload
    {
        public int Id { get; set; }
        public Nullable<int> FileId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DownloadedTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblFile tblFile { get; set; }
        public virtual tblRegister tblRegister { get; set; }
    }
}
