//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Area { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public string TelethoneNo { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<bool> IsTrainee { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Comment { get; set; }
        public string Resume { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsEmailVerify { get; set; }
        public Nullable<bool> IsContactVerify { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblState tblState { get; set; }
    }
}
